# Generated by Django 3.2 on 2021-12-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rates', to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='breakdown', to='booking.rate')),
            ],
        ),
    ]
